import { StyleSheet } from 'react-native'
import type { ThemeMode } from './types'

export const palettes = {
  light: {
    background: '#FFFFFF',
    surface: '#FFFFFF',
    surfaceSoft: '#F4F7FC',
    text: '#050816',
    muted: '#526070',
    blue: '#0B57D0',
    blueStrong: '#0643A3',
    border: '#D8E2F0',
    input: '#F8FBFF',
    segment: '#E7EEF8',
    shadow: '#071225',
  },
  dark: {
    background: '#000000',
    surface: '#242426',
    surfaceSoft: '#1C1C1E',
    text: '#FFFFFF',
    muted: '#B6B6BE',
    blue: '#FFFFFF',
    blueStrong: '#3A3A3C',
    border: '#3A3A3C',
    input: '#2C2C2E',
    segment: '#242426',
    shadow: '#000000',
  },
}

export type AppColors = (typeof palettes)[ThemeMode]

export const createStyles = (colors: AppColors) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: colors.background,
    },
    loadingScreen: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.background,
    },
    keyboardView: {
      flex: 1,
    },
    scrollContent: {
      flexGrow: 1,
      justifyContent: 'center',
      paddingBottom: 28,
      paddingHorizontal: 24,
      paddingTop: 22,
    },
    brandBlock: {
      alignItems: 'center',
      marginBottom: 22,
      width: '100%',
    },
    logo: {
      color: colors.blue,
      fontSize: 36,
      fontWeight: '900',
      marginBottom: 16,
      textAlign: 'center',
      width: '100%',
    },
    headline: {
      color: colors.text,
      fontSize: 22,
      fontWeight: '800',
      lineHeight: 29,
      marginBottom: 16,
      maxWidth: 360,
      textAlign: 'center',
    },
    themeControl: {
      alignItems: 'center',
      alignSelf: 'center',
      backgroundColor: colors.surfaceSoft,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 10,
      paddingHorizontal: 12,
      paddingVertical: 7,
    },
    themeText: {
      color: colors.muted,
      fontSize: 13,
      fontWeight: '800',
    },
    authPanel: {
      alignSelf: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      maxWidth: 390,
      padding: 18,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 14 },
      shadowOpacity: 0.12,
      shadowRadius: 26,
      width: '100%',
      elevation: 4,
    },
    segmentedControl: {
      backgroundColor: colors.segment,
      borderRadius: 8,
      flexDirection: 'row',
      marginBottom: 18,
      padding: 4,
    },
    segmentButton: {
      alignItems: 'center',
      borderRadius: 6,
      flex: 1,
      paddingVertical: 11,
    },
    segmentButtonActive: {
      backgroundColor: colors.surface,
    },
    segmentText: {
      color: colors.muted,
      fontSize: 15,
      fontWeight: '800',
    },
    segmentTextActive: {
      color: colors.blue,
    },
    formTitle: {
      color: colors.text,
      fontSize: 24,
      fontWeight: '900',
      marginBottom: 18,
      textAlign: 'center',
    },
    authLinkButton: {
      alignSelf: 'center',
      marginBottom: 10,
      marginTop: -4,
      paddingHorizontal: 8,
      paddingVertical: 6,
    },
    authLinkText: {
      color: colors.blue,
      fontSize: 14,
      fontWeight: '900',
      textAlign: 'center',
    },
    passwordHint: {
      color: colors.muted,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
      marginBottom: 10,
      marginTop: -4,
      textAlign: 'center',
    },
    appScreen: {
      flex: 1,
      backgroundColor: colors.background,
    },
    homeContent: {
      paddingBottom: 118,
      paddingHorizontal: 18,
      paddingTop: 26,
    },
    homeHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 26,
    },
    homeTitleBlock: {
      flex: 1,
      paddingRight: 12,
    },
    kicker: {
      color: colors.blue,
      fontSize: 14,
      fontWeight: '900',
      marginBottom: 6,
    },
    homeTitle: {
      color: colors.text,
      fontSize: 46,
      fontWeight: '900',
      letterSpacing: 0,
      lineHeight: 52,
    },
    homeActions: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 8,
    },
    modeButton: {
      backgroundColor: colors.surfaceSoft,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    modeButtonText: {
      color: colors.blue,
      fontSize: 13,
      fontWeight: '900',
    },
    secondaryButton: {
      backgroundColor: colors.surfaceSoft,
      borderColor: colors.border,
      borderRadius: 18,
      borderWidth: 1,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    secondaryButtonText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '800',
    },
    statsRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 14,
    },
    statCard: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 26,
      borderWidth: 1,
      flex: 1,
      padding: 14,
    },
    statValue: {
      color: colors.text,
      fontSize: 28,
      fontWeight: '900',
      marginBottom: 4,
    },
    statLabel: {
      color: colors.muted,
      fontSize: 13,
      fontWeight: '800',
    },
    summaryRow: {
      alignItems: 'center',
      borderBottomColor: colors.border,
      borderBottomWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      minHeight: 62,
      paddingVertical: 14,
    },
    summaryRowLabel: {
      color: colors.text,
      fontSize: 19,
      fontWeight: '900',
      marginBottom: 3,
    },
    summaryRowValue: {
      color: colors.text,
      fontSize: 20,
      fontWeight: '900',
      marginLeft: 12,
      textAlign: 'right',
    },
    summaryDivider: {
      backgroundColor: colors.border,
      height: 1,
      marginVertical: 10,
    },
    adminBadge: {
      alignSelf: 'flex-start',
      backgroundColor: colors.blueStrong,
      borderRadius: 8,
      marginTop: 14,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    adminBadgeText: {
      color: '#FFFFFF',
      fontSize: 13,
      fontWeight: '900',
    },
    adminStatsGrid: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 14,
    },
    calendarViewSelector: {
      backgroundColor: colors.segment,
      borderRadius: 24,
      flexDirection: 'row',
      gap: 4,
      marginBottom: 14,
      padding: 4,
    },
    calendarViewButton: {
      alignItems: 'center',
      borderRadius: 20,
      flex: 1,
      paddingVertical: 10,
    },
    calendarViewButtonActive: {
      backgroundColor: colors.blueStrong,
    },
    calendarViewText: {
      color: colors.muted,
      fontSize: 13,
      fontWeight: '900',
    },
    calendarViewTextActive: {
      color: '#FFFFFF',
    },
    calendarPanel: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 28,
      borderWidth: 1,
      marginBottom: 14,
      overflow: 'hidden',
      padding: 10,
    },
    monthBar: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 14,
    },
    iconButton: {
      alignItems: 'center',
      backgroundColor: colors.surfaceSoft,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      height: 38,
      justifyContent: 'center',
      width: 38,
    },
    iconButtonText: {
      color: colors.blue,
      fontSize: 19,
      fontWeight: '900',
    },
    monthTitle: {
      color: colors.text,
      flex: 1,
      fontSize: 20,
      fontWeight: '900',
      textAlign: 'center',
      textTransform: 'capitalize',
    },
    weekHeader: {
      flexDirection: 'row',
      marginBottom: 2,
    },
    weekdayText: {
      color: colors.muted,
      flex: 1,
      fontSize: 12,
      fontWeight: '900',
      textAlign: 'center',
    },
    calendarGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    dayCell: {
      alignItems: 'stretch',
      borderColor: colors.border,
      borderRadius: 0,
      borderWidth: 1,
      height: 114,
      justifyContent: 'flex-start',
      marginBottom: 0,
      overflow: 'hidden',
      paddingHorizontal: 3,
      paddingTop: 6,
      width: '14.2857%',
    },
    dayCellMuted: {
      opacity: 0.38,
    },
    dayCellToday: {
      borderColor: colors.blue,
    },
    dayCellSelected: {
      backgroundColor: colors.blueStrong,
      borderColor: colors.blueStrong,
    },
    dayCellHoliday: {
      borderColor: colors.blue,
      borderWidth: 2,
    },
    dayNumber: {
      color: colors.text,
      fontSize: 20,
      fontWeight: '900',
      lineHeight: 24,
    },
    dayNumberMuted: {
      color: colors.muted,
    },
    dayNumberSelected: {
      color: '#FFFFFF',
    },
    shiftDots: {
      flexDirection: 'row',
      gap: 3,
      height: 7,
      marginTop: 4,
    },
    shiftDot: {
      borderRadius: 3,
      height: 6,
      width: 6,
    },
    dayCellHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      minHeight: 24,
      paddingHorizontal: 3,
    },
    calendarShiftStack: {
      gap: 3,
      marginTop: 5,
    },
    calendarShiftPill: {
      borderRadius: 5,
      minHeight: 32,
      overflow: 'hidden',
      paddingHorizontal: 3,
      paddingVertical: 2,
    },
    calendarShiftPillText: {
      fontSize: 12,
      fontWeight: '900',
      lineHeight: 14,
      textAlign: 'center',
    },
    calendarShiftHoursText: {
      fontSize: 11,
      fontWeight: '800',
      lineHeight: 13,
      opacity: 0.78,
      textAlign: 'center',
    },
    calendarMoreText: {
      color: colors.muted,
      fontSize: 11,
      fontWeight: '900',
      textAlign: 'center',
    },
    holidayDot: {
      backgroundColor: colors.blue,
      borderRadius: 3,
      height: 6,
      width: 6,
    },
    loadingText: {
      color: colors.muted,
      fontSize: 13,
      fontWeight: '700',
      marginTop: 8,
      textAlign: 'center',
    },
    weekStrip: {
      flexDirection: 'row',
      gap: 6,
    },
    weekDayCard: {
      alignItems: 'center',
      backgroundColor: colors.surfaceSoft,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      flex: 1,
      justifyContent: 'center',
      minHeight: 84,
      paddingHorizontal: 4,
      paddingVertical: 8,
    },
    weekDayLabel: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: '900',
      marginBottom: 4,
    },
    weekDayNumber: {
      color: colors.text,
      fontSize: 19,
      fontWeight: '900',
      marginBottom: 4,
    },
    weekShiftCount: {
      color: colors.muted,
      fontSize: 10,
      fontWeight: '800',
      textAlign: 'center',
    },
    dayFocusText: {
      color: colors.muted,
      fontSize: 15,
      fontWeight: '800',
      lineHeight: 22,
      textAlign: 'center',
    },
    yearGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    yearMonthCard: {
      backgroundColor: colors.surfaceSoft,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      minHeight: 82,
      padding: 10,
      width: '31.6%',
    },
    yearMonthName: {
      color: colors.text,
      fontSize: 17,
      fontWeight: '900',
      marginBottom: 8,
      textTransform: 'capitalize',
    },
    yearMonthStats: {
      color: colors.muted,
      fontSize: 12,
      fontWeight: '800',
      marginBottom: 4,
    },
    yearMonthHours: {
      color: colors.blue,
      fontSize: 13,
      fontWeight: '900',
    },
    dayPanel: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 28,
      borderWidth: 1,
      marginBottom: 14,
      padding: 16,
    },
    panelEyebrow: {
      color: colors.blue,
      fontSize: 12,
      fontWeight: '900',
      marginBottom: 6,
      textTransform: 'uppercase',
    },
    selectedDateTitle: {
      color: colors.text,
      fontSize: 28,
      fontWeight: '900',
      marginBottom: 14,
      textTransform: 'capitalize',
    },
    shiftList: {
      gap: 10,
      marginBottom: 16,
    },
    shiftRow: {
      alignItems: 'center',
      backgroundColor: colors.surfaceSoft,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: 12,
    },
    shiftColorBar: {
      borderRadius: 8,
      height: 48,
      marginRight: 10,
      width: 6,
    },
    shiftIconBadge: {
      alignItems: 'center',
      backgroundColor: colors.background,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      height: 38,
      justifyContent: 'center',
      marginRight: 10,
      width: 38,
    },
    shiftInfo: {
      flex: 1,
      paddingRight: 10,
    },
    shiftTime: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '900',
      marginBottom: 4,
    },
    shiftMeta: {
      color: colors.muted,
      fontSize: 13,
      fontWeight: '700',
    },
    shiftNotes: {
      color: colors.muted,
      fontSize: 13,
      lineHeight: 18,
      marginTop: 6,
    },
    rowActions: {
      flexDirection: 'row',
      gap: 6,
    },
    smallIconButton: {
      alignItems: 'center',
      backgroundColor: colors.background,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      height: 34,
      justifyContent: 'center',
      width: 34,
    },
    emptyText: {
      color: colors.muted,
      fontSize: 15,
      lineHeight: 22,
      marginBottom: 16,
    },
    actionSplit: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 14,
      marginTop: 4,
    },
    actionButton: {
      alignItems: 'center',
      backgroundColor: colors.surfaceSoft,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      flex: 1,
      paddingVertical: 12,
    },
    actionButtonActive: {
      backgroundColor: colors.blueStrong,
      borderColor: colors.blueStrong,
    },
    actionButtonText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '900',
    },
    actionButtonTextActive: {
      color: '#FFFFFF',
    },
    formPanel: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 28,
      borderWidth: 1,
      marginBottom: 14,
      padding: 16,
    },
    formSectionTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '900',
      marginBottom: 8,
    },
    helperText: {
      color: colors.muted,
      fontSize: 14,
      lineHeight: 20,
      marginBottom: 14,
    },
    sectionTitle: {
      color: colors.text,
      fontSize: 32,
      fontWeight: '900',
      letterSpacing: 0,
      lineHeight: 38,
      marginBottom: 14,
      marginTop: 22,
    },
    groupedPanel: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 28,
      borderWidth: 1,
      marginBottom: 18,
      overflow: 'hidden',
      paddingHorizontal: 18,
      paddingVertical: 4,
    },
    groupedPanelTitle: {
      color: colors.text,
      fontSize: 23,
      fontWeight: '900',
      lineHeight: 29,
      paddingBottom: 14,
      paddingTop: 18,
      textAlign: 'center',
    },
    menuRow: {
      alignItems: 'center',
      borderBottomColor: colors.border,
      borderBottomWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      minHeight: 66,
      paddingVertical: 13,
    },
    menuRowContent: {
      flex: 1,
      paddingRight: 12,
    },
    menuRowTitle: {
      color: colors.text,
      fontSize: 22,
      fontWeight: '900',
      lineHeight: 27,
    },
    menuRowValue: {
      color: colors.text,
      fontSize: 22,
      fontWeight: '900',
      lineHeight: 27,
      textAlign: 'right',
    },
    menuRowDetail: {
      color: colors.muted,
      fontSize: 15,
      fontWeight: '700',
      lineHeight: 20,
      marginTop: 3,
    },
    menuChevron: {
      color: colors.text,
      fontSize: 34,
      fontWeight: '700',
      marginLeft: 8,
    },
    roundedIconBadge: {
      alignItems: 'center',
      borderRadius: 22,
      height: 44,
      justifyContent: 'center',
      marginRight: 14,
      width: 44,
    },
    footerText: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '900',
      lineHeight: 25,
      marginTop: 14,
      textAlign: 'center',
    },
    fieldGroup: {
      marginBottom: 14,
    },
    label: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '800',
      marginBottom: 8,
    },
    input: {
      backgroundColor: colors.input,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      color: colors.text,
      fontSize: 16,
      paddingHorizontal: 14,
      paddingVertical: 13,
    },
    dropdownTrigger: {
      alignItems: 'center',
      backgroundColor: colors.input,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      justifyContent: 'space-between',
      minHeight: 48,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    dropdownTriggerText: {
      color: colors.text,
      flex: 1,
      fontSize: 16,
      fontWeight: '800',
      paddingRight: 10,
    },
    dropdownList: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 6,
      marginTop: 8,
      padding: 6,
    },
    dropdownItem: {
      alignItems: 'center',
      borderRadius: 6,
      flexDirection: 'row',
      justifyContent: 'space-between',
      minHeight: 40,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    dropdownItemActive: {
      backgroundColor: colors.blueStrong,
    },
    dropdownItemText: {
      color: colors.text,
      flex: 1,
      fontSize: 14,
      fontWeight: '800',
      paddingRight: 8,
    },
    dropdownItemTextActive: {
      color: '#FFFFFF',
    },
    timeRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 14,
    },
    timeField: {
      flex: 1,
    },
    notesInput: {
      minHeight: 78,
      textAlignVertical: 'top',
    },
    colorRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    colorSwatch: {
      alignItems: 'center',
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 2,
      height: 34,
      justifyContent: 'center',
      width: 34,
    },
    colorSwatchActive: {
      borderColor: colors.text,
    },
    iconPickerRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    iconChoice: {
      alignItems: 'center',
      backgroundColor: colors.surfaceSoft,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      height: 40,
      justifyContent: 'center',
      width: 40,
    },
    iconChoiceActive: {
      backgroundColor: colors.blueStrong,
      borderColor: colors.blueStrong,
    },
    templateList: {
      gap: 0,
    },
    templateCard: {
      alignItems: 'center',
      backgroundColor: colors.surfaceSoft,
      borderColor: colors.border,
      borderRadius: 0,
      borderWidth: 0,
      borderBottomWidth: 1,
      flexDirection: 'row',
      minHeight: 78,
      paddingHorizontal: 0,
      paddingVertical: 12,
    },
    templateColor: {
      borderRadius: 23,
      height: 46,
      marginRight: 14,
      width: 46,
    },
    compactRow: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 8,
      justifyContent: 'space-between',
    },
    templateName: {
      color: colors.text,
      fontSize: 23,
      fontWeight: '900',
      marginBottom: 4,
    },
    primaryButton: {
      alignItems: 'center',
      backgroundColor: colors.blueStrong,
      borderRadius: 24,
      justifyContent: 'center',
      marginTop: 8,
      minHeight: 50,
      paddingVertical: 14,
    },
    disabledButton: {
      opacity: 0.65,
    },
    primaryButtonText: {
      color: '#FFFFFF',
      fontSize: 17,
      fontWeight: '900',
    },
    placeholderPanel: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      padding: 18,
    },
    placeholderTitle: {
      color: colors.text,
      fontSize: 22,
      fontWeight: '900',
      marginBottom: 10,
    },
    placeholderText: {
      color: colors.muted,
      fontSize: 16,
      lineHeight: 24,
    },
    bottomNav: {
      alignItems: 'center',
      backgroundColor: colors.surfaceSoft,
      borderColor: colors.border,
      borderRadius: 36,
      borderWidth: 1,
      bottom: 10,
      elevation: 12,
      flexDirection: 'row',
      justifyContent: 'space-between',
      left: 18,
      padding: 5,
      position: 'absolute',
      right: 18,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.34,
      shadowRadius: 18,
    },
    bottomNavItem: {
      alignItems: 'center',
      borderRadius: 31,
      flex: 1,
      justifyContent: 'center',
      minHeight: 64,
      paddingHorizontal: 2,
      paddingVertical: 6,
    },
    bottomNavCenter: {
      marginHorizontal: 2,
    },
    bottomNavItemActive: {
      backgroundColor: colors.blueStrong,
    },
    bottomNavLabel: {
      color: colors.muted,
      fontSize: 10,
      fontWeight: '900',
      marginTop: 4,
      textAlign: 'center',
    },
    bottomNavLabelActive: {
      color: '#FFFFFF',
    },
    configPanel: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      margin: 24,
      padding: 18,
    },
    configText: {
      color: colors.muted,
      fontSize: 16,
      lineHeight: 24,
      marginBottom: 14,
    },
    configCode: {
      backgroundColor: colors.surfaceSoft,
      borderRadius: 6,
      color: colors.text,
      fontSize: 13,
      marginTop: 8,
      padding: 10,
    },
  })

export type AppStyles = ReturnType<typeof createStyles>
